***-------------------------------------------------------------------------------------------------***;
*** Macro Name:    mm_dsinfo.sas                                                                    ***;
*** Purpose:       Write dataset existence, observation count, variable count, and label to the log.***;
***-------------------------------------------------------------------------------------------------***;
*** Programmed By: Manivannan Mathialagan                                                           ***;
*** Created On:    16Sep2026                                                                        ***;
***                                                                                                 ***;
***-------------------------------------------------------------------------------------------------***;
*** Note:          This macro is intended for personal programming, development, and debugging      ***;
***                use only and is not a study-standard or production macro.                       ***;
***-------------------------------------------------------------------------------------------------***;
*** Parameters                                                                                      ***;
***-------------------------------------------------------------------------------------------------***;
*** Name     | Description                                            | Default value   | Required  ***;
***----------|--------------------------------------------------------|-----------------|-----------***;
*** DS       | Input SAS dataset or view                              | No default      | Yes       ***;
***-------------------------------------------------------------------------------------------------***;
*** Output(s):      Compact dataset summary in the SAS log. No datasets are created.                ***;
*** Dependencies:  None a missing dataset is reported as an error.                                  ***;
***-------------------------------------------------------------------------------------------------***;
*** Modification History                                                                            ***;
***-------------------------------------------------------------------------------------------------***;
*** Date        | Modified By            | Description                                              ***;
***-------------|------------------------|----------------------------------------------------------***;
*** 16Sep2026   | Manivannan Mathialagan | Initial version created                                  ***;
***-------------------------------------------------------------------------------------------------***;

%macro mm_dsinfo(ds=);
    %local _mm_dsid _mm_rc _mm_nobs _mm_nvars _mm_label;
    %if not %sysfunc(exist(&ds)) and not %sysfunc(exist(&ds,view)) %then %do;
        %put ERROR: [MM_DSINFO] Dataset &ds does not exist.;
        %return;
    %end;

    %let _mm_dsid=%sysfunc(open(&ds,i));
    %if &_mm_dsid %then %do;
        %let _mm_nobs=%sysfunc(attrn(&_mm_dsid,nlobs));
        %let _mm_nvars=%sysfunc(attrn(&_mm_dsid,nvars));
        %let _mm_label=%sysfunc(attrc(&_mm_dsid,label));
        %let _mm_rc=%sysfunc(close(&_mm_dsid));
        %put NOTE: [MM_DSINFO] Dataset=&ds Observations=&_mm_nobs Variables=&_mm_nvars Label=&_mm_label;
    %end;
    %else %put ERROR: [MM_DSINFO] Dataset &ds could not be opened.;
%mend mm_dsinfo;
