***-------------------------------------------------------------------------------------------------***;
*** Macro Name:    mm_macvars.sas                                                                   ***;
*** Purpose:       Display selected macro variable names, scopes, and resolved values in the log.   ***;
***-------------------------------------------------------------------------------------------------***;
*** Programmed By: Manivannan Mathialagan                                                           ***;
*** Created On:    16Sep2026                                                                        ***;
***                                                                                                 ***;
***-------------------------------------------------------------------------------------------------***;
*** Note:          This macro is intended for personal programming, development, and debugging      ***;
***                use only and is not a study-standard or production macro.                        ***;
***-------------------------------------------------------------------------------------------------***;
*** Parameters                                                                                      ***;
***-------------------------------------------------------------------------------------------------***;
*** Name     | Description                                            | Default value   | Required  ***;
***----------|--------------------------------------------------------|-----------------|-----------***;
*** VARS     | Space-separated macro variable names without ampersand | No default      | Yes       ***;
***-------------------------------------------------------------------------------------------------***;
*** Output(s):      Clearly delimited messages in the SAS log. No datasets are created.             ***;
*** Dependencies:  None undefined macro variables are reported rather than resolved.                ***;
***-------------------------------------------------------------------------------------------------***;
*** Modification History                                                                            ***;
***-------------------------------------------------------------------------------------------------***;
*** Date        | Modified By            | Description                                              ***;
***-------------|------------------------|----------------------------------------------------------***;
*** 16Sep2026   | Manivannan Mathialagan | Initial version created                                  ***;
***-------------------------------------------------------------------------------------------------***;

%macro mm_macvars(vars=);
    %local _mm_i _mm_name _mm_scope _mm_value _mm_nvars;
    %let _mm_nvars=%sysfunc(countw(%superq(vars),%str( )));

    %put NOTE: ------------------------------------------------------------------;
    %put NOTE: [MM_MACVARS] Selected macro variables;
    %do _mm_i=1 %to &_mm_nvars;
        %let _mm_name=%scan(%superq(vars),&_mm_i,%str( ));
        %if %symexist(&_mm_name) %then %do;
            %let _mm_scope=%sysfunc(symglobl(&_mm_name));
            %if &_mm_scope %then %let _mm_scope=GLOBAL;
            %else %let _mm_scope=LOCAL;
            %let _mm_value=%superq(&_mm_name);
            %put NOTE: [MM_MACVARS] &_mm_name (&_mm_scope) = &_mm_value;
        %end;
        %else %put WARNING: [MM_MACVARS] &_mm_name is not defined.;
    %end;
    %put NOTE: ------------------------------------------------------------------;
%mend mm_macvars;
