***-------------------------------------------------------------------------------------------------***;
*** Macro Name:    mm_sort.sas                                                                      ***;
*** Purpose:       Create a sorted copy of a dataset for temporary investigation.                   ***;
***-------------------------------------------------------------------------------------------------***;
*** Programmed By: Manivannan Mathialagan                                                           ***;
*** Created On:    16Sep2026                                                                        ***;
***                                                                                                 ***;
***-------------------------------------------------------------------------------------------------***;
*** Note:          This macro is intended for personal programming, development, and debugging      ***;
***                use only and is not a study-standard or production macro.                        ***;
***-------------------------------------------------------------------------------------------------***;
*** Parameters                                                                                      ***;
***-------------------------------------------------------------------------------------------------***;
*** Name     | Description                                            | Default value   | Required  ***;
***----------|--------------------------------------------------------|-----------------|-----------***;
*** DS       | Input SAS dataset                                      | No default      | Yes       ***;
*** BY       | Sort variables and optional DESCENDING keywords        | No default      | Yes       ***;
*** OUT      | Output sorted dataset                                  | _MM_SORTED      | No        ***;
*** WHERE    | WHERE condition used to filter observations            | Blank           | No        ***;
*** NODUPKEY | Remove records with duplicate BY= values               | N               | No        ***;
***-------------------------------------------------------------------------------------------------***;
*** Output(s):      Dataset specified in OUT=.                                                      ***;
*** Dependencies:  BY= variables must exist in DS=.                                                 ***;
***-------------------------------------------------------------------------------------------------***;
*** Modification History                                                                            ***;
***-------------------------------------------------------------------------------------------------***;
*** Date        | Modified By            | Description                                              ***;
***-------------|------------------------|----------------------------------------------------------***;
*** 16Sep2026   | Manivannan Mathialagan | Initial version created                                  ***;
***-------------------------------------------------------------------------------------------------***;

%macro mm_sort(ds=, by=, out=_mm_sorted, where=, nodupkey=N);
    proc sort data=&ds
        %if %length(%superq(where)) %then %do; (where=(%unquote(&where))) %end;
        out=&out
        %if %upcase(&nodupkey)=Y %then nodupkey;
        ;
        by &by;
    run;
    %put NOTE: [MM_SORT] Sorted dataset &out created from &ds by &by.;
%mend mm_sort;
